[workspace]
resolver = "2"
members = [
    "crates/hyper-core",
    "crates/hyper-pkg",
    "crates/hfe-cli",
    "crates/launcher",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Xznder1984"]
repository = "https://github.com/Xznder1984/Hyper-FNF-Engine"
rust-version = "1.87"

[workspace.dependencies]
hyper-core = { path = "crates/hyper-core" }
hyper-pkg = { path = "crates/hyper-pkg" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1.1"
anyhow = "1"
thiserror = "2"