use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let engines_dir = manifest_dir.join("../../engines");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let target = out_dir.join("engines");
    fs::create_dir_all(&target).unwrap();

    println!("cargo:rerun-if-changed={}", engines_dir.display());

    let mut gen = String::new();
    gen.push_str("// generated by build.rs - do not edit\n");

    let mut entries: Vec<_> = Vec::new();
    if let Ok(rd) = fs::read_dir(&engines_dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.extension().map(|x| x == "toml").unwrap_or(false) {
                entries.push(p);
            }
        }
    }
    entries.sort();

    for p in &entries {
        let file_name = p.file_name().unwrap().to_string_lossy().to_string();
        let stem = p.file_stem().unwrap().to_string_lossy().replace('-', "_");
        let const_name = stem.to_uppercase();
        fs::copy(p, target.join(&file_name)).unwrap();
        gen.push_str(&format!(
            "pub const {const_name}: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/engines/{file_name}\"));\n"
        ));
    }

    let module = out_dir.join("engines_generated.rs");
    fs::write(module, gen).unwrap();
    println!(
        "cargo:rerun-if-changed={}",
        out_dir.join("engines_generated.rs").display()
    );
}
