use std::path::PathBuf;

use hyper_core::{detect, engine::EngineLibrary, settings::Settings};

use crate::out;

#[derive(clap::Args, Debug)]
pub struct Args {
    /// Directory to initialise (defaults to the current directory)
    #[arg(default_value = ".")]
    path: PathBuf,

    /// Print what would happen without changing anything
    #[arg(long)]
    dry_run: bool,

    /// Do not ask for confirmation
    #[arg(long)]
    yes: bool,
}

pub fn run(args: Args) -> i32 {
    let root = if args.path.as_os_str() == "." {
        std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    } else {
        args.path.clone()
    };

    match init_dir(&root, args.dry_run, args.yes) {
        Ok(code) => code,
        Err(e) => {
            out::fail(&e.to_string());
            e.exit_code()
        }
    }
}

fn init_dir(root: &std::path::Path, dry_run: bool, yes: bool) -> hyper_core::Result<i32> {
    out::status("init", &format!("target: {}", root.display()));
    if !root.exists() {
        out::fail(&format!("path does not exist: {}", root.display()));
        return Ok(1);
    }
    if !root.is_dir() {
        out::fail(&format!("path is not a directory: {}", root.display()));
        return Ok(1);
    }

    let mut entries = std::fs::read_dir(root)?.collect::<Result<Vec<_>, _>>()?;
    entries.retain(|e| e.file_name() != ".hyper");
    let names: Vec<String> = entries
        .iter()
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();

    if names.is_empty() {
        // empty folder: safe to write config
        if dry_run {
            out::note("would create .hyper/config.toml (empty directory, no mod yet)");
            return Ok(0);
        }
        if let Err(e) = write_config(root, None, None) {
            out::fail(&format!("could not create .hyper/config.toml: {e}"));
            return Ok(1);
        }
        out::ok("initialised (no mod detected)");
        out::note("point a mod here or run 'hfe run <mod-dir>' when ready");
        return Ok(0);
    }

    // non-empty: detect a mod, never touch user files
    let settings = Settings::load()?;
    let lib = EngineLibrary::load()?;
    let det = detect::detect(root, &lib, &settings);

    if let Some(engine_id) = &det.engine_id {
        out::status(
            "detected",
            &format!(
                "{} (confidence: {})",
                engine_id,
                det.confidence.as_str()
            ),
        );
        for ev in &det.evidence {
            out::note(ev);
        }
        if det.confidence == detect::Confidence::Low {
            out::warn("confidence is low; you can pin an engine later with: hfe run --engine <id>");
        }
        if !dry_run {
            write_config(root, Some(engine_id), None)?;
            out::ok(&format!("wrote .hyper/config.toml (engine: {engine_id})"));
        } else {
            out::note(&format!(
                "would write .hyper/config.toml (engine: {engine_id})"
            ));
        }
    } else {
        out::warn("no supported FNF mod structure detected in this folder");
        for n in names.iter().take(12) {
            out::note(&format!("present: {n}"));
        }
        out::note("existing files are never touched by 'hfe init'");
        if !dry_run {
            let proceed = crate::cmd::confirm(
                "create .hyper/config.toml here anyway (no mod detected)?",
                yes,
            );
            if proceed {
                write_config(root, None, None)?;
                out::ok("initialised without an engine (detection will run on 'hfe run')");
            } else {
                out::note("aborted (nothing changed)");
            }
        }
    }
    Ok(0)
}

fn write_config(root: &std::path::Path, engine: Option<&str>, version: Option<&str>) -> hyper_core::Result<()> {
    let dir = root.join(".hyper");
    std::fs::create_dir_all(&dir)?;
    let version_line = match version {
        Some(v) => format!("{v:?}"),
        None => "null".to_string(),
    };
    let engine_line = match engine {
        Some(e) => format!("{e:?}"),
        None => "null".to_string(),
    };
    let config = format!(
        "# generated by 'hfe init' - edit freely\nengine = {engine_line}\nengine_version = {version_line}\n"
    );
    std::fs::write(dir.join("config.toml"), config)?;
    Ok(())
}